<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInsectesNonAmis($user)
    {
        if(count($user->getAmis()) == 0)
            return $this->findAllOtherUsers($user);

        $qb = $this->createQueryBuilder('u');
        $query = $qb->select('u')
                ->AndWhere('u.id != :id')
                ->setParameter('id', $user->getId())
                ->andWhere($qb->expr()->notIn('u', ':amis'))
                ->setParameter('amis', $user->getAmis())
                ->getQuery();

        return $query->getResult();
    }

    public function findAllOtherUsers($user) {
        return $this->createQueryBuilder('u')
            ->where('u.id != :id')
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
