user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE

user_detailsAmis:
    path:     /{id}/detailsAmis
    defaults: { _controller: "AppBundle:User:detailsAmis" }
    methods:  GET

user_detailsInsecte:
    path:     /{id}/detailsInsecte
    defaults: { _controller: "AppBundle:User:detailsInsecte" }
    methods:  GET

user_addAmis:
    path:     /{id}/add
    defaults: { _controller: "AppBundle:User:addAmis" }
    methods:  GET

user_removeAmis:
    path:     /{id}/remove
    defaults: { _controller: "AppBundle:User:removeAmis" }
    methods:  GET